const API_URL = process.env.REACT_APP_API_URL;
const GIT_ACCESS_TOKEN = process.env.REACT_APP_GIT_ACCESS_TOKEN;
const PAGINATION_ITEMS_PER_PAGE = 50;

export { API_URL, PAGINATION_ITEMS_PER_PAGE, GIT_ACCESS_TOKEN };
